baseURL = ''
languageCode = 'zh-cn'
title = "Zhou's Blog"
theme = 'ananke'

[taxonomies]
  category = 'categories'
  tag = 'tags'

[[menu.main]]
name = "About"
url = "/about"

[[menu.main]]
name = "WebDaily"
url = "/webdaily"
 